title: Arnab Neelim Mazumder
logo: /headshot_circle.jpg
description: PhD Candidate@UMBC, Visiting Research scholar@JHU, Ex-Intern@Infineon Technologies

# Site Author
author:
  name             : "Jack Dougherty"
  avatar           : "images/portfolio/jackdougherty2023.jpg"
  bio              : "Professor and Director of Educational Studies at Trinity College, Hartford CT, USA"
  # location         : " "
  # email            : " "
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:jack.dougherty@trincoll.edu
    - label: "Calendar"
      icon: "fas fa-fw fa-calendar-alt"
      url: "https://jackdougherty.youcanbook.me"
    - label: "Mastodon"  #Custom verification: _includes/head/custom.html
      icon: "fab fa-fw fa-mastodon"
      url: "https://urbanists.social/@jackdougherty"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jackdougherty"
    - label: "JackBikes.org"
      icon: "fas fa-fw fa-bicycle"
      url: "https://jackbikes.org"

show_downloads: false
theme: jekyll-theme-minimal
# theme: jekyll-theme-primer
