title: Arnab Neelim Mazumder
logo: /headshot_circle.jpg
description: PhD Candidate@UMBC, Visiting Research scholar@JHU, Ex-Intern@Infineon Technologies
show_downloads: false
theme: jekyll-theme-minimal
# theme: jekyll-theme-primer
