title: Arnab Neelim Mazumder
logo: /headshot_circle.jpg
description: Postdoc@LANL, Ex-PhD@UMBC, Ex-Visiting Research Scholar@JHU, Ex-Intern@Infineon Technologies
show_downloads: false
theme: jekyll-theme-minimal
# theme: jekyll-theme-primer
