title: Arnab Neelim Mazumder
logo: /headshot_circle.png
description: I am a graduate student at UMBC pursuing a PhD in Computer Engineering with both academic and internship experience in developing explainable deep learning modules for audios and images as well as their deployment on embedded devices. Specialties include but are not limited to Python, MATLAB, C Programming, TensorFlow, PyTorch, and Verilog. Previously, I worked as an intern at Infineon Technologies with a focus on building transparent and interpretable AI models.
show_downloads: false
theme: jekyll-theme-minimal
# theme: jekyll-theme-primer
